=== Abhishek-Maurya-D/Web-Technology/HTML/email.dtd
<!ELEMENT email (header,body,attachment)>
<!ELEMENT header (from, to, subject, date)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!ELEMENT body (#PCDATA)>

<!ELEMENT attachments (attachment)>
<!ELEMENT attachment (filetype, filename)>
<!ELEMENT filetype (#PCDATA)>
<!ELEMENT filename (#PCDATA)>

<!ATTLIST email id CDATA #REQUIRED>
<!ATTLIST from email CDATA #REQUIRED>
<!ATTLIST to email CDATA #REQUIRED>
<!ATTLIST attachment size CDATA #IMPLIED>

=== Abhishek-Maurya-D/Web-Technology/HTML/email.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email SYSTEM 'email.dtd'>
<email id="email001">
    <header>
        <from email="john.doe@example.com">John Doe</from>
        <to email="jane.doe@example.com">Jane Doe</to>
        <subject>Meeting Reminder</subject>
        <date>2024/10/17</date>
    </header>
    <body>
        This is a meeting reminder for the scheduled meeting tomorrow at 10 A.M.
    </body>
    <attachment>
        <attachments size="2MB">
            <filename>meeting.agenda.pdf</filename>
            <filetype>application/pdf</filetype>
        </attachments>
    </attachment>
</email>
