=== Abhishek-Maurya-D/Web-Technology/HTML/myemail.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="email">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="from">
                                <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="email" type="xs:string"/>
                                    </xs:extension>
                                </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="to">
                                <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="email" type="xs:string"/>
                                    </xs:extension>
                                </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="subject" type="xs:string"/>
                            <xs:element name="date" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body" type="xs:string"/>
                <xs:element name="attachments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attachment">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="filename" type="xs:string"/>
                            <xs:element name="filetype" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="size" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
                </xs:element>
            </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Abhishek-Maurya-D/Web-Technology/HTML/email2.xml
<?xml version="1.0" encoding="UTF-8"?>
<email
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="myemail.xsd"
id="email001">
    <header>
        <from email="john.doe@example.com">John Doe</from>
        <to email="jane.doe@example.com">Jane Doe</to>
        <subject>Meeting Reminder</subject>
        <date>2024-09-25</date>
    </header>
    <body>
        This is a reminder for our meeting scheduled tomorrow at 10 AM.
    </body>
    <attachments>
        <attachment size="2MB">
            <filename>meeting_agenda.pdf</filename>
            <filetype>application/pdf</filetype>
        </attachment>
    </attachments>
</email>
